controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

deals_statistics:
    path: /leads/statistics
    controller: App\Controller\LeadsController::getLeadsStatistics
    methods: [GET]
